"""Add SEC data tables

Revision ID: 846c3c4d7d71
Revises: d2e9f4877223
Create Date: 2025-12-14 10:30:18.398190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '846c3c4d7d71'
down_revision: Union[str, None] = 'd2e9f4877223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('institution_id', sa.Integer(), nullable=False))
    op.add_column('filings', sa.Column('total_holdings', sa.Integer(), nullable=True))
    op.add_column('filings', sa.Column('raw_response', sa.Text(), nullable=True))
    op.alter_column('filings', 'accession_no',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('ix_filings_cik', table_name='filings')
    op.drop_index('ix_filings_form_type', table_name='filings')
    op.create_index(op.f('ix_filings_institution_id'), 'filings', ['institution_id'], unique=False)
    op.drop_constraint('filings_cik_fkey', 'filings', type_='foreignkey')
    op.create_foreign_key(None, 'filings', 'institutions', ['institution_id'], ['id'])
    op.drop_column('filings', 'total_holdings_count')
    op.drop_column('filings', 'company_name')
    op.drop_column('filings', 'cik')
    op.drop_column('filings', 'raw_data')
    op.add_column('holdings', sa.Column('shares_or_prn_amt', sa.BigInteger(), nullable=True))
    op.add_column('holdings', sa.Column('shares_or_prn_amt_type', sa.String(length=10), nullable=True))
    op.alter_column('holdings', 'cusip',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('holdings', 'ticker',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('holdings', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('holdings', 'investment_discretion',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('holdings', 'voting_authority_sole',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('holdings', 'voting_authority_shared',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('holdings', 'voting_authority_none',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index('idx_filing_cusip', table_name='holdings')
    op.drop_index('idx_filing_ticker', table_name='holdings')
    op.create_index(op.f('ix_holdings_filing_id'), 'holdings', ['filing_id'], unique=False)
    op.drop_constraint('holdings_filing_id_fkey', 'holdings', type_='foreignkey')
    op.create_foreign_key(None, 'holdings', 'filings', ['filing_id'], ['id'])
    op.drop_column('holdings', 'other_manager')
    op.drop_column('holdings', 'put_call')
    op.drop_column('holdings', 'shares_or_principal_amount')
    op.drop_column('holdings', 'shares_or_principal_type')
    op.drop_index('ix_institutions_name', table_name='institutions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_institutions_name', 'institutions', ['name'], unique=False)
    op.add_column('holdings', sa.Column('shares_or_principal_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('holdings', sa.Column('shares_or_principal_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('holdings', sa.Column('put_call', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('holdings', sa.Column('other_manager', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.create_foreign_key('holdings_filing_id_fkey', 'holdings', 'filings', ['filing_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_holdings_filing_id'), table_name='holdings')
    op.create_index('idx_filing_ticker', 'holdings', ['filing_id', 'ticker'], unique=False)
    op.create_index('idx_filing_cusip', 'holdings', ['filing_id', 'cusip'], unique=False)
    op.alter_column('holdings', 'voting_authority_none',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('holdings', 'voting_authority_shared',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('holdings', 'voting_authority_sole',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('holdings', 'investment_discretion',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('holdings', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('holdings', 'ticker',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('holdings', 'cusip',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=9),
               nullable=True)
    op.drop_column('holdings', 'shares_or_prn_amt_type')
    op.drop_column('holdings', 'shares_or_prn_amt')
    op.add_column('filings', sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('filings', sa.Column('cik', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('filings', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('filings', sa.Column('total_holdings_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'filings', type_='foreignkey')
    op.create_foreign_key('filings_cik_fkey', 'filings', 'institutions', ['cik'], ['cik'])
    op.drop_index(op.f('ix_filings_institution_id'), table_name='filings')
    op.create_index('ix_filings_form_type', 'filings', ['form_type'], unique=False)
    op.create_index('ix_filings_cik', 'filings', ['cik'], unique=False)
    op.alter_column('filings', 'accession_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('filings', 'raw_response')
    op.drop_column('filings', 'total_holdings')
    op.drop_column('filings', 'institution_id')
    # ### end Alembic commands ###
