"""Add SEC data models

Revision ID: d2e9f4877223
Revises: c90f6940a5d6
Create Date: 2025-12-14 10:22:17.166868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e9f4877223'
down_revision: Union[str, None] = 'c90f6940a5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_cik'), 'institutions', ['cik'], unique=True)
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_no', sa.String(length=30), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=False),
    sa.Column('period_of_report', sa.String(length=20), nullable=True),
    sa.Column('link_to_filing_details', sa.Text(), nullable=True),
    sa.Column('link_to_txt', sa.Text(), nullable=True),
    sa.Column('link_to_html', sa.Text(), nullable=True),
    sa.Column('total_holdings_count', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['institutions.cik'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filings_accession_no'), 'filings', ['accession_no'], unique=True)
    op.create_index(op.f('ix_filings_cik'), 'filings', ['cik'], unique=False)
    op.create_index(op.f('ix_filings_filed_at'), 'filings', ['filed_at'], unique=False)
    op.create_index(op.f('ix_filings_form_type'), 'filings', ['form_type'], unique=False)
    op.create_index(op.f('ix_filings_id'), 'filings', ['id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('name_of_issuer', sa.String(length=255), nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('shares_or_principal_amount', sa.Float(), nullable=True),
    sa.Column('shares_or_principal_type', sa.String(length=10), nullable=True),
    sa.Column('put_call', sa.String(length=10), nullable=True),
    sa.Column('investment_discretion', sa.String(length=10), nullable=True),
    sa.Column('other_manager', sa.String(length=10), nullable=True),
    sa.Column('voting_authority_sole', sa.Float(), nullable=True),
    sa.Column('voting_authority_shared', sa.Float(), nullable=True),
    sa.Column('voting_authority_none', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_filing_cusip', 'holdings', ['filing_id', 'cusip'], unique=False)
    op.create_index('idx_filing_ticker', 'holdings', ['filing_id', 'ticker'], unique=False)
    op.create_index(op.f('ix_holdings_cusip'), 'holdings', ['cusip'], unique=False)
    op.create_index(op.f('ix_holdings_id'), 'holdings', ['id'], unique=False)
    op.create_index(op.f('ix_holdings_name_of_issuer'), 'holdings', ['name_of_issuer'], unique=False)
    op.create_index(op.f('ix_holdings_ticker'), 'holdings', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holdings_ticker'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_name_of_issuer'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_cusip'), table_name='holdings')
    op.drop_index('idx_filing_ticker', table_name='holdings')
    op.drop_index('idx_filing_cusip', table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_filings_id'), table_name='filings')
    op.drop_index(op.f('ix_filings_form_type'), table_name='filings')
    op.drop_index(op.f('ix_filings_filed_at'), table_name='filings')
    op.drop_index(op.f('ix_filings_cik'), table_name='filings')
    op.drop_index(op.f('ix_filings_accession_no'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_cik'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
